stock:
  type     : rest
  resource : App\Controller\StockController
  prefix   : /api/


repas:
  type     : rest
  resource : App\Controller\RepasController
  prefix   : /api/

commande:
  type     : rest
  resource : App\Controller\CommandeController
  prefix   : /api/

