# api_login_check:
#   path: /api/login_check

# gesdinet_jwt_refresh_token:
#   path: api/token/refresh
#   controller: gesdinet.jwtrefreshtoken::refresh

# comment:
#   type     : rest
#   resource : App\Controller\CommentController
#   prefix   : /api/

# movie:
#   type     : rest
#   resource : App\Controller\MovieController
#   prefix   : /api/

# user:
#   type     : rest
#   resource : App\Controller\UserController
#   prefix   : /api/

stock:
  type     : rest
  resource : App\Controller\StockController
  prefix   : /api/


repas:
  type     : rest
  resource : App\Controller\RepasController
  prefix   : /api/
